blog/urls.py
from django.urls import path

from blog.views import PostListView, PostDetailView, CategoryPostListView, TagPostListView, SearchPostListView, CommentCreateView, CommentDeleteView,ReplyCreateView, ReplyDeleteView


urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("category/<str:slug>/", CategoryPostListView.as_view(), name="category-post-list"),
    path("tag/<str:slug>/", TagPostListView.as_view(), name="tag-post-list"),
    path("search/", SearchPostListView.as_view(), name="search-post-list"),
    path("comment/<int:post_pk>/", CommentCreateView.as_view(), name="comment"),
    path("comment/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),                                       path("reply/<int:pk>/delete/", ReplyDeleteView.as_view(), name="reply-delete"),          
    path("reply/<int:comment_pk>/", ReplyCreateView.as_view(), name="reply"),                                                                                               
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("markdownx/", include("markdownx.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

blog/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class Category(models.Model):
    name = models.CharField(verbose_name="カテゴリー", max_length=255)
    slug = models.SlugField(verbose_name="URL", unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "カテゴリー"
        verbose_name_plural = "カテゴリー"


class Tag(models.Model):
    name = models.CharField(verbose_name="タグ", max_length=255)
    slug = models.SlugField(verbose_name="URL", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "タグ"
        verbose_name_plural = "タグ"
        

class Post(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=200)
    # content = models.TextField(verbose_name="本文")
    content = MarkdownxField(verbose_name="本文")
    image = models.ImageField(verbose_name='画像', upload_to="uploads/", null=True, blank=True)
    created_at = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="更新日", auto_now=True)
    is_published = models.BooleanField(verbose_name="公開設定", default=False)

    category = models.ForeignKey(Category, verbose_name="カテゴリー", on_delete=models.PROTECT, null=True, blank=True)

    tags = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)

    def convert_markdown_to_html(self):
        return markdownify(self.content)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "記事"
        verbose_name_plural = "記事"

class Comment(models.Model):
    name = models.CharField(verbose_name="名前", max_length=100)
    text = models.TextField(verbose_name="本文")
    created_at = models.DateTimeField(verbose_name="作成日", auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="記事")

    def __str__(self):
        return self.text[:10]

    class Meta:
        verbose_name = "コメント"
        verbose_name_plural = "コメント"
        

class Reply(models.Model):
    name = models.CharField(verbose_name="名前", max_length=100)
    text = models.TextField(verbose_name="本文")
    created_at = models.DateTimeField(verbose_name="作成日", auto_now_add=True)

    comment = models.ForeignKey(Comment, verbose_name="コメント", on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:10]

    class Meta:
        verbose_name = "返信"
        verbose_name_plural = "返信"

blog/forms.py
from django import forms

from blog.models import Comment, Reply


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "text")
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "名前", "class": "form-control"}),
            "text": forms.Textarea(attrs={"placeholder": "コメントを入力してください。", "class": "form-control"}),
        }
        labels = {
            "name": "※必須",
            "text": "※必須",
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ("name", "text")
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "名前", "class": "form-control"}),
            "text": forms.Textarea(attrs={"placeholder": "コメントを入力してください。", "class": "form-control"}),
        }
        labels = {
            "name": "※必須",
            "text": "※必須",
        }

blog/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from blog.models import Post, Category, Tag, Comment, Reply
from blog.forms import CommentForm, ReplyForm

posts_per_page = 5

class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    # paginate_by = 1

    def get_queryset(self):
        posts = super().get_queryset()
        return posts.order_by("-updated_at")

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        if post.is_published or self.request.user.is_authenticated:
            return post
        else:
            raise Http404

class CategoryPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = posts_per_page

    def get_queryset(self):
        slug = self.kwargs["slug"]
        self.category = get_object_or_404(Category, slug=slug)
        return super().get_queryset().filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        return context

class TagPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = posts_per_page

    def get_queryset(self):
        slug = self.kwargs["slug"]
        self.tag = get_object_or_404(Tag, slug=slug)
        return super().get_queryset().filter(tags=self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context
        
class SearchPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = posts_per_page

    def get_queryset(self):
        self.query = self.request.GET.get("query") or ""
        queryset = super().get_queryset()

        if self.query:
            queryset = queryset.filter(
                Q(title__icontains=self.query) | Q(content__icontains=self.query)
            )

        if not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True)

        self.post_count = len(queryset)    

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.query
        return context
    
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)

        post_pk = self.kwargs["post_pk"]
        post = get_object_or_404(Post, pk=post_pk)

        comment.post = post
        comment.save()
        return redirect("post-detail", pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs["post_pk"]
        context["post"] = get_object_or_404(Post, pk=post_pk)
        return context

class ReplyCreateView(CreateView):
    model = Reply
    form_class = ReplyForm
    template_name = "blog/comment_form.html"

    def form_valid(self, form):
        reply = form.save(commit=False)

        comment_pk = self.kwargs["comment_pk"]
        comment = get_object_or_404(Comment, pk=comment_pk)

        reply.comment = comment
        reply.save()
        return redirect("post-detail", pk=comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs["comment_pk"]
        context["comment"] = get_object_or_404(Comment, pk=comment_pk)
        return context
    
class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = "blog/comment_delete.html"
    # success_url = reverse_lazy("post-detail")

    def get_success_url(self):
        return reverse("post-detail", kwargs={"pk": self.object.post.pk})
    
class ReplyDeleteView(LoginRequiredMixin, DeleteView):
    model = Reply
    template_name = "blog/comment_delete.html"

    def get_success_url(self):
        return reverse("post-detail", kwargs={"pk": self.object.comment.post.pk})

blog/templates/blog/snippets/comments.html
{% if post.comment_set.all %}
<hr>
<h4 class="mb-4">コメント一覧</h4>
{% for comment in post.comment_set.all %}
<div class="comment mb-4">
    <b class="mb-2">{{ comment.name }} {{ comment.created_at }}</b>
    <a href="{% url 'reply' comment.pk %}"><i class="fa-solid fa-reply"></i></a>    
    
    {% if user.is_authenticated %}
    <a href="{% url 'comment-delete' comment.pk %}"><i class="fa-solid fa-trash-can"></i></a>
    {% endif %}
    <p>{{ comment.text }}</p>    

    {% for reply in comment.reply_set.all %}
    <div class="reply ms-4">
        <b>{{ reply.name }} {{ reply.created_at }}</b>
        {% if user.is_authenticated %}
        <a href="{% url 'reply-delete' reply.pk %}"><i class="fa-solid fa-trash-can"></i></a>
        {% endif %}
        <p>{{ reply.text }}</p>
    </div>
    {% endfor %}
</div>
{% endfor %}
{% endif %}

blog/templates/blog/snippets/footer.html
<footer class="mt-5">
  <p><span lang="en">©</span>Djangoブログ</p>
</footer>

blog/templates/blog/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light shadow-sm p-3 mb-5 bg-body rounded">
  <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'post-list' %}">Djangoブログ</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <form  action="{% url 'search-post-list' %}" method="GET" class="d-flex me-2">
            <input class="form-control me-2" type="text" name="query" placeholder="キーワードを入力" value="{{ query }}">
            <input class="btn btn-outline-success" type="submit" value="検索">
          </form>
      </div>
  </nav>

blog/templates/blog/snippets/pagination.html
{% load blog %}

{% if page_obj.has_previous %}
<!-- <a href="?page={{ page_obj.previous_page_number }}">前へ</a> -->
<a href="?{%  replace request 'page' page_obj.previous_page_number %}">前へ</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<span>{{ num }}</span>
{% else %}
<!-- <a href="?page={{ num }}">{{ num }}</a> -->
<a href="?{%  replace request 'page' num %}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<!-- <a href="?page={{ page_obj.next_page_number }}">次へ</a> -->
<a href="?{%  replace request 'page' page_obj.next_page_number %}">次へ</a>
{% endif %}

blog/templates/blog/snippets/sidebar.html
<div class = "p-4 category">
  <h4>カテゴリー</h4>
  <ul class="list-group list-group-flush">
    {% for category in categories %}

    {% if category.count > 0 %}
    <li class="list-group-item">
      <a href="{% url 'category-post-list' category.slug %}">{{category.name}}({{category.count}})</a>
    </li>
    {% endif %}

    {% endfor %}
  </ul>   
</div>
<div class = "p-4">
  <h4>タグ</h4>

  {% for tag in tags %}
  <a class="btn btn-light bg-light text-dark m-1" href="{% url 'tag-post-list' tag.slug %}">{{tag.name}}</a>
  {% endfor %}
</div>